### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by eson57** [rpadovani/100balls#9]
Hi,

Nice game! Here's a Swedish translation if you want it. Hope you'll complete the language template.

eson

**Comment by rpadovani** [comment]
Hi Åke,
thanks for your time :-)

Unfortunately, I didn't update the template since last June, so this translation is old.

If you wan to translate the appit, I just updated the .pot file. 

I'll be more than happy to include it. 

Thanks in advance :-)

**Comment by eson57** [comment]
Hi again,
Thanks for updating. Here's the new file then...
https://svenskasprakfiler.se/tempfiles/100balls-sv_SE.po

**Comment by rpadovani** [comment]
Thank you very much!
I included it in the code, unfortunately I have some issues with Ubuntu SDK so I don't know when I'll release an update with your translations.

Thanks  :-)
